console.log('Script file connected...');

let container = document.querySelector('.container');
    container.style.border = '1px solid black';
    container.style.padding = '20px 10px';
    container.style.margin = '40px auto';
    container.style.maxWidth = '550px';
    
    let gridSquare1 = document.createElement('div');
    let gridSquare2 = document.createElement('div');
    let gridSquare3 = document.createElement('div');
    let gridSquare4 = document.createElement('div');
    let gridSquare5 = document.createElement('div');
    let gridSquare6 = document.createElement('div');
    let gridSquare7 = document.createElement('div');
    let gridSquare8 = document.createElement('div');
    let gridSquare9 = document.createElement('div');
    let gridSquare10 = document.createElement('div');
    let gridSquare11 = document.createElement('div');
    let gridSquare12 = document.createElement('div');
    let gridSquare13 = document.createElement('div');
    let gridSquare14 = document.createElement('div');
    let gridSquare15 = document.createElement('div');
    let gridSquare16 = document.createElement('div');

container.appendChild(gridSquare1);
container.appendChild(gridSquare2);
container.appendChild(gridSquare3);
container.appendChild(gridSquare4);
container.appendChild(gridSquare5);
container.appendChild(gridSquare6);
container.appendChild(gridSquare7);
container.appendChild(gridSquare8);
container.appendChild(gridSquare9);
container.appendChild(gridSquare10);
container.appendChild(gridSquare11);
container.appendChild(gridSquare12);
container.appendChild(gridSquare13);
container.appendChild(gridSquare14);
container.appendChild(gridSquare15);
container.appendChild(gridSquare16);